# Generated by Django 4.1.7 on 2023-12-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0027_rename_myphotos_myphoto_delete_interests_and_more'),
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companion',
            name='companions',
            field=models.ManyToManyField(related_name='companions', to='head.profile'),
        ),
    ]
