# Generated by Django 4.1.7 on 2023-12-23 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_alter_companion_companions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companion',
            old_name='companions',
            new_name='companion',
        ),
    ]
