# Generated by Django 4.1.7 on 2023-12-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0031_remove_profile_companions'),
        ('messenger', '0004_alter_message_companion_delete_companion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companion', models.ManyToManyField(related_name='companions', to='head.profile')),
            ],
        ),
    ]
