# Generated by Django 4.1.7 on 2024-01-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0007_alter_message_companion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
