# Generated by Django 4.2.2 on 2023-10-08 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0002_profile_username_alter_profile_hobbies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='customer',
            new_name='user',
        ),
    ]
