# Generated by Django 4.2.2 on 2023-10-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0003_rename_customer_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
