# Generated by Django 4.2.2 on 2023-10-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0004_alter_profile_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hobbies',
        ),
        migrations.AddField(
            model_name='profile',
            name='hobbies',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
