# Generated by Django 4.2.2 on 2023-10-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0005_remove_profile_hobbies_profile_hobbies'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('В активном поиске', 'В активном поиске'), ('Влюблен(а)', 'Влюблен(а)'), ('Встречается', 'Встречается'), ('В гражданском браке', 'В гражданском браке'), ('Помолвлен(а)', 'Помолвлен(а)'), ('Женат(Замужем)', 'Женат(Замужем)'), ('Все сложно', 'Все сложно'), ('Не женат(Не замужем)', 'Не женат(Не замужем)')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
