# Generated by Django 4.2.2 on 2023-10-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0007_searchpeople'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchPeople',
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'мужчина'), ('female', 'женщина'), ('trans', 'трансформер')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
