# Generated by Django 4.2.2 on 2023-10-16 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0014_alter_news_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
