# Generated by Django 4.2.2 on 2023-10-18 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('head', '0015_delete_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('---', '---'), ('male', 'мужчина'), ('female', 'женщина'), ('trans', 'трансформер')], max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hobbies',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default-profile-photo.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('В активном поиске', 'В активном поиске'), ('Влюблен(а)', 'Влюблен(а)'), ('Встречается', 'Встречается'), ('В гражданском браке', 'В гражданском браке'), ('Помолвлен(а)', 'Помолвлен(а)'), ('Женат(Замужем)', 'Женат(Замужем)'), ('Все сложно', 'Все сложно'), ('Не женат(Не замужем)', 'Не женат(Не замужем)')], max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
