# Generated by Django 4.2.2 on 2023-10-18 17:06

from django.db import migrations, models
import head.models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0016_delete_chatroom_remove_profile_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='', verbose_name=head.models.Profile)),
            ],
        ),
    ]
