# Generated by Django 4.1.7 on 2023-10-19 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0019_profile_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='head.profile'),
        ),
        migrations.AlterModelTable(
            name='profile',
            table='photos',
        ),
    ]
