# Generated by Django 4.1.7 on 2023-10-20 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0022_alter_profile_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myphotos',
            name='images',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='my_photo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='photos',
        ),
        migrations.AddField(
            model_name='myphotos',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='myphotos',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='head.profile'),
        ),
    ]
