# Generated by Django 4.1.7 on 2023-10-21 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0023_remove_myphotos_images_remove_profile_my_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myphotos',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_photos', to='head.profile'),
        ),
    ]
