# Generated by Django 4.1.7 on 2023-10-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0024_alter_myphotos_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myphotos',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='my_photos/'),
        ),
    ]
