# Generated by Django 4.1.7 on 2023-12-11 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0025_alter_myphotos_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_name',
        ),
        migrations.AlterModelTable(
            name='profile',
            table=None,
        ),
    ]
