# Generated by Django 4.1.7 on 2023-12-17 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0026_remove_profile_user_name_alter_profile_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyPhotos',
            new_name='MyPhoto',
        ),
        migrations.DeleteModel(
            name='Interests',
        ),
        migrations.RemoveField(
            model_name='like',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='like',
            name='to_user',
        ),
        migrations.RemoveField(
            model_name='match',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='user2',
        ),
        migrations.DeleteModel(
            name='SliderImage',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
