# Generated by Django 4.1.7 on 2023-12-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0027_rename_myphotos_myphoto_delete_interests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='companions',
            field=models.ManyToManyField(related_name='companions', to='head.profile'),
        ),
    ]
