# Generated by Django 4.1.7 on 2023-12-24 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0030_alter_profile_companions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='companions',
        ),
    ]
