# Generated by Django 4.1.7 on 2024-03-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0032_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('---', '---'), ('мужчина', 'мужчина'), ('женщина', 'женщина')], max_length=255),
        ),
    ]
