# Generated by Django 4.1.7 on 2024-03-20 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0033_alter_profile_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birthday',
            new_name='age',
        ),
    ]
